---
- name: Adding PPA for LXD repo
  shell: "sudo add-apt-repository -y ppa:ubuntu-lxc/lxd-stable"
  become: true
- name: Apt update
  apt: update_cache=yes
  become: true
- name: Installing Go
  apt: name=golang state=present install_recommends=yes
  become: true