---
- hosts: all
  remote_user: ubuntu
  roles:
    - role: all
    - role: users
    - role: golang
    - role: python35
    - role: nodejs
    - role: bind
    - role: gandi-dns
    - role: dwg-dotfiles
    - role: nginx
    - role: docker
    - role: ssh

- hosts: bach
  remote_user: ubuntu
  roles:
    - role: blog
    - role: irc-client
    - role: java
    - role: jupyter
    #- role: mysql
    #- role: jenkins
    - role: elasticsearch
    - role: logstash
    - role: kibana
    - role: beats

- hosts: all
  roles:
    - role: slack_done
