---
- name: Installing packages needed for Lychee.
  apt: name={{ item }} install_recommends=yes state=present
  become: true
  items:
    - php5
    - php5-cli
    - php5-gd
    - php5-mysqlnd
    - php5-curl
    - php5-json
    - imagemagick
- name: PHP Max Runtime of 3mins
  lineinfile: dest="/etc/php5/fpm/php.ini" state=present regexp="^max_execution_time.*" line="max_execution_time=180"
  become: true
- name: PHP POST Max Size of 100M
  lineinfile: dest="/etc/php5/fpm/php.ini" state=present regexp="^post_max_size.*" line="post_max_size = 100M"
  become: true
- name: PHP Max Size of 100M
  lineinfile: dest="/etc/php5/fpm/php.ini" state=present regexp="upload_max_size.*" line="upload_max_size = 100M"
  become: true
- name: PHP Max Filesize of 100M
  lineinfile: dest="/etc/php5/fpm/php.ini" state=present regexp="upload_max_filesize.*" line="upload_max_filesize = 100M"
  become: true
- name: PHP memory limit of 256M
  lineinfile: dest="/etc/php5/fpm/php.ini" state=present regexp="memory_limit.*" line="memory_limit = 256M"
  become: true
- name: PHP dont guess at filenames
  lineinfile: dest="/etc/php5/fpm/php.ini" state=present insertafter=";cgi.fix_pathinfo=1" line="cgi.fix_pathinfo=0"
  become: true
- name: Add a user for photos
  user: name='photos' comment='Photos' password='*' uid=5001 state=present shell='/bin/bash' home='/opt/lychee'
  become: true
- name: Attach the photos_data volume
  local_action: os_server_volume state=present cloud=ovh server=bach volume="655f55f7-f5b8-4a64-a631-f2bac7c9c955" device=/dev/vdc
- name: Create mount point for photos_data
  file: path=/data/photos state=directory mode=0755 owner=photos group=photos
  become: true
- name: Mount the photos data
  mount: name=/data/photos src=/dev/vdc fstype=ext4 opts=rw state=mounted
  become: true
- name: Create the lychee directory for the gallery software
  file: path=/opt/lychee state=directory mode=0755 owner=photos group=photos
  become: true
- name: Extract the latest Lychee build into /opt/lychee
  git: clone=yes dest=/opt/lychee/photos repo="https://github.com/electerious/Lychee.git" force=yes
  become: true
- name: Unlink data
  file: state=absent force=yes dest=/opt/lychee/photos/data
  become: true
- name: Unlink uploads
  file: state=absent force=yes dest=/opt/lychee/photos/uploads
  become: true
- name: Symlink data
  file: state=link force=yes src=/data/photos/data dest=/opt/lychee/photos/data
  become: true
- name: Symlink uploads
  file: state=link force=yes src=/data/photos/data dest=/opt/lychee/photos/uploads
  become: true
- name: Copy the config.php file into place
  template: src=roles/photos/files/config.php dest=/opt/lychee/photos/data/config.php owner=photos group=photos mode=0644
  become: true