#! /bin/sh
### BEGIN INIT INFO
# Provides:          jupyter
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts juypter in the correct Virtualenv
# Description:       This file should be used to construct scripts to be
#                    placed in /etc/init.d.
### END INIT INFO

# Author: David Groves
# Do NOT "set -e"

# PATH should only include /usr/* if it runs after the mountnfs.sh script
PATH=/sbin:/usr/sbin:/bin:/usr/bin
SCRIPTNAME=/etc/init.d/juypter


do_start()
{
    # We need to run start-jupyter as the jupyter user.
    sudo -u jupyter -i /opt/jupyter/start-jupyter.sh

}

#
# Function that stops the daemon/service
#
do_stop()
{
    slay jupyter
}

#
# Function that sends a SIGHUP to the daemon/service
#
do_reload() {
	#
	# If the daemon can reload its configuration without
	# restarting (for example, when it is sent a SIGHUP),
	# then implement that here.
	#
	do_stop
	do_start
}



case "$1" in
  start)
	do_start
	;;
  stop)
	do_stop
	;;
  reload)
    do_reload
    ;;
  restart)
    do_reload
    ;;
  status)
	echo "Unsupported"
	;;
esac