---
- name: Add the node key
  shell: "wget -qO - https://deb.nodesource.com/gpgkey/nodesource.gpg.key | sudo apt-key add -"
  become: true
- name: Add the node repo
  apt_repository: repo='deb https://deb.nodesource.com/node_5.x trusty main' state=present
  become: true
- name: Apt update
  apt: update_cache=yes
  become: true
- name: Installing node
  apt: name={{ item }} state=present install_recommends=yes
  with_items:
    - nodejs
  become: true