---
- name: Install elasticdump
  npm: name=elasticdump global=yes state=present
  become: true
- name: Adding signing key for elasticsearch repo
  shell: "wget -qO - https://packages.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -"
  become: true
- name: Adding logstash repo
  apt_repository: repo='deb http://packages.elastic.co/kibana/4.4/debian stable main' state=present
  become: true
- name: Apt update
  apt: update_cache=yes
  become: true
- name: Installing kibana
  apt: name=kibana state=present install_recommends=yes
  become: true
- name: Only listen on localhost
  lineinfile: >
    dest=/opt/kibana/config/kibana.yml
    insertafter='# server.host: "0.0.0.0"'
    line='server.host: "127.0.0.1"'
  become: true
- name: Listen on /kibana
  lineinfile: >
    dest=/opt/kibana/config/kibana.yml
    insertafter='# server.basePath: ""'
    line='server.basePath: "/kibana"'
  become: true
- name: Get the beats dashboards
  git: force=yes dest=/opt/beats-dashboards/ clone=yes repo=https://github.com/elastic/beats-dashboards
  become: true
- name: Import the beats dashboards
  command: /opt/beats-dashboards/load.sh
  become: true
- name: Restart kibana
  service: name=kibana state=restarted enabled=yes
  become: true