---
- name: Creating ssh keys
  file: path=/root/.ssh/ state=directory mode=0700 owner=root group=root
  become: true
- name: Copying root ssh private keys
  copy: content={{ secrets_root_ssh_private_key }} dest=/root/.ssh/id_rsa mode=0600 owner=root group=root
  become: true
- name: Copying root ssh public keys
  copy: content={{ secrets_root_ssh_public_key }} dest=/root/.ssh/id_rsa.pub mode=0600 owner=root group=root
  become: true
- name: Add root key to authorized_keys
  copy: content={{ secrets_root_ssh_public_key }} dest=/root/.ssh/authorized_keys mode=0600 owner=root group=root
  become: true
- copy: src=roles/ssh/files/{{ ansible_hostname }}/ssh_host_dsa_key dest=/etc/ssh/ssh_host_dsa_key
  become: true
- copy: src=roles/ssh/files/{{ ansible_hostname }}/ssh_host_dsa_key.pub dest=/etc/ssh/ssh_host_dsa_key.pub
  become: true
- copy: src=roles/ssh/files/{{ ansible_hostname }}/ssh_host_ecdsa_key dest=/etc/ssh/ssh_host_ecdsa_key
  become: true
- copy: src=roles/ssh/files/{{ ansible_hostname }}/ssh_host_ecdsa_key.pub dest=/etc/ssh/ssh_host_ecdsa_key.pub
  become: true
- copy: src=roles/ssh/files/{{ ansible_hostname }}/ssh_host_ed25519_key dest=/etc/ssh/ssh_host_ed25519_key
  become: true
- copy: src=roles/ssh/files/{{ ansible_hostname }}/ssh_host_ed25519_key.pub dest=/etc/ssh/ssh_host_ed25519.key.pub
  become: true
- copy: src=roles/ssh/files/{{ ansible_hostname }}/ssh_host_rsa_key dest=/etc/ssh/ssh_host_rsa_key
  become: true
- copy: src=roles/ssh/files/{{ ansible_hostname }}/ssh_host_rsa_key.pub dest=/etc/ssh/ssh_host_rsa_key.pub
  become: true
- name: Restart Ansible
  service: name=ssh state=restarted
  become: true
