---
- name: Add the repo for media
  apt_repository: repo='ppa:mc3man/trusty-media' state=present
  become: true
- name: Apt update
  apt: update_cache=yes
  become: true
- name: Installing ffmpeg
  apt: name=ffmpeg state=present install_recommends=yes
  become: true