---
- name: Creating the /data/ directory
  file: path=/data/ state=directory mode=0755 owner=root group=root
  become: true
- name: Create the /data/blog/ directory for the source of the blog
  file: path=/data/blog state=directory mode=0755 owner=dwg group=dwg
  become: true
- name: Creating the /data/websites/ directory
  file: path=/data/websites state=directory mode=0755 owner=dwg group=dwg
  become: true
- name: Creating the /data/websites/blog/ directory for the blog
  file: path=/data/websites/blog state=directory mode=0755 owner=dwg group=dwg
  become: true