---
- name: Install the Google libpam authenticator module
  apt: name='libpam-google-authenticator' state=present
  become: true
- name: Add group for David Groves
  group: name='dwg' gid=1001 state=present
  become: true
- name: Add group for Eleni Groves
  group: name='leni' gid=1002 state=present
  become: true
- name: Add user for David Groves
  user: name='dwg' comment='David Groves' password={{ secrets_users_dwg_password }} uid=1001 group='dwg' groups='sudo,lpadmin' state=present shell='/bin/bash'
  become: true
- name: Add SSH key for David Groves
  authorized_key: user='dwg' key={{ secrets_users_dwg_sshkey }} state=present
  become: true
- name: Add user for Eleni Groves
  user: name='leni' comment='Eleni Groves' password={{ secrets_users_leni_password }} uid=1002 group='leni' groups='sudo,lpadmin' state=present shell='/bin/bash'
  become: true
- name: Add Google authenticator file for David Groves
  copy: content={{ secrets_users_dwg_googleauth }} dest=/home/dwg/.google_authenticator mode=0600 owner=dwg group=dwg
  become: true
- name: Configure ssh to allow challenge response auth
  lineinfile: dest=/etc/ssh/sshd_config regexp='ChallengeResponseAuthentication no' line='ChallengeResponseAuthentication yes'
  become: true
- name: Require either a password/google auth token or an SSH key for SSH
  lineinfile: dest=/etc/pam.d/sshd insertafter=EOF line="auth       required     pam_google_authenticator.so"
  become: true
- name: Restart Openssh
  service: name=ssh state=restarted
  become: true