---
- name: Install elasticsearch-curator
  pip: name={{ item }}
       chdir=/opt/jupyter
       virtualenv=/opt/jupyter/venv
       virtualenv_python=python3
       state=present
       executable=pip3
  with_items:
    - elasticsearch-curator
  become: true
- name: Adding signing key for elasticsearch repo
  shell: "wget -qO - https://packages.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -"
  become: true
- name: Adding elasticsearch repo
  apt_repository: repo='deb http://packages.elastic.co/elasticsearch/2.x/debian stable main' state=present
  become: true
- name: Apt update
  apt: update_cache=yes
  become: true
- name: Installing elasticsearch
  apt: name={{ item }} state=present install_recommends=yes
  become: true
  with_items:
    - elasticsearch
- name: Only listen on localhost
  lineinfile: >
    dest=/etc/elasticsearch/elasticsearch.yml
    insertafter="# network.host: 192.168.0.1"
    line="network.host: localhost"
  become: true
- name: Restart elasticsearch
  service: name=elasticsearch state=restarted enabled=yes
  become: true