---
- name: Adding apt repo for Docker
  command: "sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D"
  become: true
- name: Adding elasticsearch repo
  apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-trusty main' state=present
  become: true
- name: Apt update
  apt: update_cache=yes
  become: true
- name: Install docker
  apt: name={{ item }} state=present install_recommends=yes
  become: true
  with_items:
    - docker-engine