---
- name: Add the PPA for opendnssec
  command: add-apt-repository -y ppa:pkg-opendnssec/ppa
  become: true
- name: Add the PPA for a modern version of bind
  command: add-apt-repository -y ppa:mgrocock/bind9
  become: true
- name: Install Bind
  apt: name=bind9 state=present
  become: true
- name: Delete rndc.key as we replace it
  file: dest=/etc/bind/rndc.key state=absent
  become: true
- name: Install bind9utils
  apt: name=bind9utils state=present
  become: true
- name: Create zones directory
  file: dest=/etc/bind/zones state=directory mode=0755 owner=bind group=bind
  become: true
- name: Create keys directory
  file: dest=/etc/bind/keys state=directory mode=0755 owner=bind group=bind
  become: true
- name: Copying named.conf.local
  template: src=roles/bind/files/named.conf.local dest=/etc/bind/named.conf.local owner=bind group=bind mode=0644
  become: true
- name: Copying named.conf.options
  template: src=roles/bind/files/named.conf.options dest=/etc/bind/named.conf.options owner=bind group=bind mode=0644
  become: true
- name: Copying copperdog.org zone from template
  template: src=roles/bind/files/zones/copperdog.org dest=/etc/bind/zones/copperdog.org owner=bind group=bind mode=0644
  become: true
- name: Copying copperdog.org zone from template
  template: src=roles/bind/files/zones/as5607.net dest=/etc/bind/zones/as5607.net owner=bind group=bind mode=0644
  become: true
- name: Copy apparmor profile for named
  template: src=roles/bind/files/usr.sbin.named dest=/etc/apparmor.d/local/usr.sbin.named owner=root group=root mode=0600
  become: true
- name: Copy rndc.conf
  template: src=roles/bind/files/rndc.conf dest=/etc/bind/rndc.conf owner=bind group=bind mode=0600
  become: true
- name: Touch /var/log/bind.log
  file: path=/var/log/bind.log state=touch mode=0755 owner=bind group=bind
  become: true
- name: Copy the resign shell script
  copy: src=files/resign.sh dest=/usr/local/sbin/resign.sh owner=bind group=bind mode=0755
  become: true
  when: ansible_hostname == "bach"
- name: Run resign shell script (for copperdog.org)
  shell: /usr/local/sbin/resign.sh copperdog.org
  become: true
  when: ansible_hostname == "bach"
- name: Run resign shell script (for as5607.net)
  shell: /usr/local/sbin/resign.sh as5607.net
  become: true
  when: ansible_hostname == "bach"
- name: Restart apparmor
  service: name=apparmor state=restarted
  become: true
- name: Restart bind9
  service: name=bind9 state=restarted
  become: true